//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignature.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ddrempeCryptography")]
        public string FolderPath {
            get {
                return ((string)(this["FolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tajni_kljuc.txt")]
        public string SymmetricCryptographySecretKeyFileName {
            get {
                return ((string)(this["SymmetricCryptographySecretKeyFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VerySecret")]
        public string SymmetricCryptographyPassphrase {
            get {
                return ((string)(this["SymmetricCryptographyPassphrase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text_for_encryption.txt")]
        public string PlainTextFileName {
            get {
                return ((string)(this["PlainTextFileName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("symmetric_encrypted.txt")]
        public string SymmetricCryptographyEncryptedFileName {
            get {
                return ((string)(this["SymmetricCryptographyEncryptedFileName"]));
            }
            set {
                this["SymmetricCryptographyEncryptedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("symmetric_decrypted.txt")]
        public string SymmetricCryptographyDecryptedFileName {
            get {
                return ((string)(this["SymmetricCryptographyDecryptedFileName"]));
            }
            set {
                this["SymmetricCryptographyDecryptedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("asymmetric_encrypted.txt")]
        public string AsymmetricCryptographyEncryptedFileName {
            get {
                return ((string)(this["AsymmetricCryptographyEncryptedFileName"]));
            }
            set {
                this["AsymmetricCryptographyEncryptedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("asymmetric_decrypted.txt")]
        public string AsymmetricCryptographyDecryptedFileName {
            get {
                return ((string)(this["AsymmetricCryptographyDecryptedFileName"]));
            }
            set {
                this["AsymmetricCryptographyDecryptedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("javni_kljuc.txt")]
        public string AsymmetricCryptographyPublicKeyFileName {
            get {
                return ((string)(this["AsymmetricCryptographyPublicKeyFileName"]));
            }
            set {
                this["AsymmetricCryptographyPublicKeyFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("privatni_kljuc.txt")]
        public string AsymmetricCryptographyPrivateKeyFileName {
            get {
                return ((string)(this["AsymmetricCryptographyPrivateKeyFileName"]));
            }
            set {
                this["AsymmetricCryptographyPrivateKeyFileName"] = value;
            }
        }
    }
}
